### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by patdx** [patdx/gh-release-browser#2]
- [ ] https://gh-release-browser.pages.dev/cloudflare/workers-sdk For some reason 0.0.34 is sorted as newer than 3.42.0
- [ ] https://gh-release-browser.pages.dev/facebook/react has a lot of "failed to parse"
- [ ] A lot of repos randomly have "failed to parse" releases
- [ ] Set meta tags (and og image?) for each repo's page
- [ ] Design a better display format, such as grouping releases by major/minor
- [ ] Inline release notes
- [ ] Submit an issue button that links to GitHub
